backend:
  name: git-gateway
  branch: master
media_folder: "public/images/uploads"
site_url: "https://championsofcommerce.com"
# logo_url: https://your-site.com/images/logo.svg
# locale: "en"
show_preview_links: true
view_filters:
  - label: "Faves"
    field: "category"
    pattern: "faves"
  - label: "Craves"
    field: "category"
    pattern: "craves"
  - label: "Retail"
    field: "category"
    pattern: "retail"
  - label: "Services"
    field: "category"
    pattern: "services"
collections:
  - name: "businesses"
    label: "Businesses"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["faves", "craves", "retail", "service"],
        }
      - { label: "Website", name: "website", widget: "string", required: false }
      - {
          label: "Gift Card Link",
          name: "giftCardLink",
          widget: "string",
          required: false,
        }
      - {
          label: "Gift Card Number",
          name: "giftCardNumber",
          widget: "string",
          required: false,
        }
      - {
          label: "Offers Pickup",
          name: "pickup",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Offers Delivery",
          name: "delivery",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Masks Are Required",
          name: "masksRequired",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Employees Wear Masks",
          name: "employeesMasked",
          widget: "boolean",
          default: true,
        }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
